---
dev_mode: false
motor_x:
  max_step_speed: 200
  pull_gpio: 18
  dir_gpio: 27
  ena_gpio: ~
  end_left_gpio: 21
  end_right_gpio: 20
  step_size: 0.004
motor_y:
  max_step_speed: 200
  pull_gpio: 22
  dir_gpio: 23
  ena_gpio: ~
  end_left_gpio: 19
  end_right_gpio: 26
  step_size: 0.004
motor_z:
  max_step_speed: 200
  pull_gpio: 25
  dir_gpio: 24
  ena_gpio: ~
  end_left_gpio: 5
  end_right_gpio: 6
  step_size: 0.004
calibrate_z_gpio: 16
input_dir:
  - "."
input_update_reduce: 10
default_speed: 5.0
rapid_speed: 50.0
scaler: 1.0
invert_z: false
show_console_output: false
console_pos_update_reduce: 50
