---
devMode: true
motorX:
  maxStepSpeed: 200
  pullGpio: 18
  dirGpio: 27
  endLeftGpio: 21
  endRightGpio: 20
  stepSize: 0.004
motorY:
  maxStepSpeed: 200
  pullGpio: 22
  dirGpio: 23
  endLeftGpio: 19
  endRightGpio: 26
  stepSize: 0.004
motorZ:
  maxStepSpeed: 200
  pullGpio: 25
  dirGpio: 24
  endLeftGpio: 5
  endRightGpio: 6
  stepSize: 0.004
calibrateZGpio: 16
inputDir:
  - "."
  - /home/alex
inputUpdateReduce: 10
defaultSpeed: 5.0
rapidSpeed: 50.0
scale: 1.0
invertZ: false
showConsoleOutput: false
consolePosUpdateReduce: 50